export type GroupOrderScreen = {
  n: number;
  nodeId: string;
  figmaName: string;
  title: string;
  note: string;
  width: number;
  height: number;
  src: string;
};

export type GroupOrderFlow = {
  id: string;
  figma: number;
  label: string;
  short: string;
  description: string;
  screens: GroupOrderScreen[];
};

export const FIGMA_FILE = "NialMl3AkkpfNy6UxQr0h2";
export const FIGMA_SECTION = "300:92379";

export const FLOWS: GroupOrderFlow[] = [
  {
    id: "flujo-1",
    figma: 1,
    label: "Flujo 1 · Rest+Turbo",
    short: "Rest+Turbo",
    description: "Figma 2nd review · Restaurante + Turbo. Pedido de verticales distintas (McDonald’s + Turbo) en un carrito, un checkout y un pago.",
    screens: [
      {
        n: 1,
        nodeId: "259:76932",
        figmaName: "Flow 1 - 1",
        title: "Cover",
        note: "Portada o corte de diseño (slides 2.0) en el flujo de Figma.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-1/flow-1-01.png",
      },
      {
        n: 2,
        nodeId: "290:67843",
        figmaName: "Flow 1 - 2",
        title: "Cover",
        note: "Portada o corte de diseño (slides 2.0) en el flujo de Figma.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-1/flow-1-02.png",
      },
      {
        n: 3,
        nodeId: "290:65054",
        figmaName: "Flow 1 - 3",
        title: "Tienda",
        note: "Storefront.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-1/flow-1-03.png",
      },
      {
        n: 4,
        nodeId: "290:65050",
        figmaName: "Flow 1 - 4",
        title: "Tienda · canasta",
        note: "Storefront con el botón de canasta.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-1/flow-1-04.png",
      },
      {
        n: 5,
        nodeId: "290:65046",
        figmaName: "Flow 1 - 5",
        title: "Tienda · canasta",
        note: "Storefront con el botón de canasta.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-1/flow-1-05.png",
      },
      {
        n: 6,
        nodeId: "290:65042",
        figmaName: "Flow 1 - 6",
        title: "Tienda · canasta",
        note: "Storefront con el botón de canasta.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-1/flow-1-06.png",
      },
      {
        n: 7,
        nodeId: "290:65024",
        figmaName: "Flow 1 - 7",
        title: "Modal",
        note: "Modal o bottom sheet sobre la pantalla.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-1/flow-1-07.png",
      },
      {
        n: 8,
        nodeId: "290:65006",
        figmaName: "Flow 1 - 8",
        title: "Modal",
        note: "Modal o bottom sheet sobre la pantalla.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-1/flow-1-08.png",
      },
      {
        n: 9,
        nodeId: "290:64988",
        figmaName: "Flow 1 - 9",
        title: "Modal",
        note: "Modal o bottom sheet sobre la pantalla.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-1/flow-1-09.png",
      },
      {
        n: 10,
        nodeId: "290:64964",
        figmaName: "Flow 1 - 10",
        title: "Modal",
        note: "Modal o bottom sheet sobre la pantalla.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-1/flow-1-10.png",
      },
      {
        n: 11,
        nodeId: "290:64940",
        figmaName: "Flow 1 - 11",
        title: "Modal",
        note: "Modal o bottom sheet sobre la pantalla.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-1/flow-1-11.png",
      },
      {
        n: 12,
        nodeId: "290:64916",
        figmaName: "Flow 1 - 12",
        title: "Modal",
        note: "Modal o bottom sheet sobre la pantalla.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-1/flow-1-12.png",
      },
      {
        n: 13,
        nodeId: "259:76930",
        figmaName: "Flow 1 - 13",
        title: "Cover",
        note: "Portada o corte de diseño (slides 2.0) en el flujo de Figma.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-1/flow-1-13.png",
      },
      {
        n: 14,
        nodeId: "258:72897",
        figmaName: "Flow 1 - 14",
        title: "Canasta",
        note: "Canasta agrupada.",
        width: 375,
        height: 1716,
        src: "./assets/group-order/flujo-1/flow-1-14.png",
      },
      {
        n: 15,
        nodeId: "258:74820",
        figmaName: "Flow 1 - 15",
        title: "Canasta",
        note: "Canasta agrupada.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-1/flow-1-15.png",
      },
      {
        n: 16,
        nodeId: "258:75450",
        figmaName: "Flow 1 - 16",
        title: "Canasta",
        note: "Canasta agrupada.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-1/flow-1-16.png",
      },
      {
        n: 17,
        nodeId: "258:76121",
        figmaName: "Flow 1 - 17",
        title: "Canasta",
        note: "Canasta agrupada.",
        width: 375,
        height: 1572,
        src: "./assets/group-order/flujo-1/flow-1-17.png",
      },
      {
        n: 18,
        nodeId: "290:67863",
        figmaName: "Flow 1 - 18",
        title: "Canasta",
        note: "Canasta agrupada.",
        width: 375,
        height: 1712,
        src: "./assets/group-order/flujo-1/flow-1-18.png",
      },
      {
        n: 19,
        nodeId: "293:69242",
        figmaName: "Flow 1 - 19",
        title: "Tienda · canasta",
        note: "Storefront con el botón de canasta.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-1/flow-1-19.png",
      },
      {
        n: 20,
        nodeId: "293:69163",
        figmaName: "Flow 1 - 20",
        title: "Canasta",
        note: "Canasta agrupada.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-1/flow-1-20.png",
      },
      {
        n: 21,
        nodeId: "259:76996",
        figmaName: "Flow 1 - 21",
        title: "Cover",
        note: "Portada o corte de diseño (slides 2.0) en el flujo de Figma.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-1/flow-1-21.png",
      },
      {
        n: 22,
        nodeId: "263:83136",
        figmaName: "Flow 1 - 22",
        title: "Checkout",
        note: "Checkout (dirección / pago).",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-1/flow-1-22.png",
      },
      {
        n: 23,
        nodeId: "253:64423",
        figmaName: "Flow 1 - 23",
        title: "Checkout · modal",
        note: "Checkout con modal.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-1/flow-1-23.png",
      },
      {
        n: 24,
        nodeId: "263:82202",
        figmaName: "Flow 1 - 24",
        title: "Checkout",
        note: "Checkout (dirección / pago).",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-1/flow-1-24.png",
      },
      {
        n: 25,
        nodeId: "259:77008",
        figmaName: "Flow 1 - 25",
        title: "Cover",
        note: "Portada o corte de diseño (slides 2.0) en el flujo de Figma.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-1/flow-1-25.png",
      },
      {
        n: 26,
        nodeId: "295:75150",
        figmaName: "Flow 1 - 26",
        title: "Checkout",
        note: "Checkout unificado.",
        width: 375,
        height: 1581,
        src: "./assets/group-order/flujo-1/flow-1-26.png",
      },
      {
        n: 27,
        nodeId: "296:75686",
        figmaName: "Flow 1 - 27",
        title: "Checkout",
        note: "Checkout unificado.",
        width: 375,
        height: 1545,
        src: "./assets/group-order/flujo-1/flow-1-27.png",
      },
      {
        n: 28,
        nodeId: "296:75626",
        figmaName: "Flow 1 - 28",
        title: "Checkout",
        note: "Checkout unificado.",
        width: 375,
        height: 2023,
        src: "./assets/group-order/flujo-1/flow-1-28.png",
      },
      {
        n: 29,
        nodeId: "295:75134",
        figmaName: "Flow 1 - 29",
        title: "Cover",
        note: "Portada o corte de diseño (slides 2.0) en el flujo de Figma.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-1/flow-1-29.png",
      },
      {
        n: 30,
        nodeId: "296:77308",
        figmaName: "Flow 1 - 30",
        title: "Pedido creado",
        note: "Confirmación de la orden padre.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-1/flow-1-30.png",
      },
      {
        n: 31,
        nodeId: "296:77399",
        figmaName: "Flow 1 - 31",
        title: "Pedido creado",
        note: "Confirmación de la orden padre.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-1/flow-1-31.png",
      },
      {
        n: 32,
        nodeId: "295:75132",
        figmaName: "Flow 1 - 32",
        title: "Cover",
        note: "Portada o corte de diseño (slides 2.0) en el flujo de Figma.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-1/flow-1-32.png",
      },
      {
        n: 33,
        nodeId: "297:81729",
        figmaName: "Flow 1 - 33",
        title: "Home",
        note: "Home Rappi.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-1/flow-1-33.png",
      },
      {
        n: 34,
        nodeId: "297:81716",
        figmaName: "Flow 1 - 34",
        title: "Home",
        note: "Home Rappi.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-1/flow-1-34.png",
      },
      {
        n: 35,
        nodeId: "297:78755",
        figmaName: "Flow 1 - 35",
        title: "Tracking",
        note: "Order tracking / detalle de sub-orden.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-1/flow-1-35.png",
      },
      {
        n: 36,
        nodeId: "297:79598",
        figmaName: "Flow 1 - 36",
        title: "Tracking · tooltip",
        note: "Detalle de tracking con tooltip.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-1/flow-1-36.png",
      },
      {
        n: 37,
        nodeId: "297:80087",
        figmaName: "Flow 1 - 37",
        title: "Tracking · mapa",
        note: "Order tracking con mapa de una sub-orden.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-1/flow-1-37.png",
      },
      {
        n: 38,
        nodeId: "297:81703",
        figmaName: "Flow 1 - 38",
        title: "Home",
        note: "Home Rappi.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-1/flow-1-38.png",
      },
      {
        n: 39,
        nodeId: "297:80422",
        figmaName: "Flow 1 - 39",
        title: "Tracking",
        note: "Order tracking / detalle de sub-orden.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-1/flow-1-39.png",
      },
      {
        n: 40,
        nodeId: "297:80494",
        figmaName: "Flow 1 - 40",
        title: "Tracking · tooltip",
        note: "Detalle de tracking con tooltip.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-1/flow-1-40.png",
      },
      {
        n: 41,
        nodeId: "297:80404",
        figmaName: "Flow 1 - 41",
        title: "Tracking · modal",
        note: "Tracking con sheet o código de entrega.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-1/flow-1-41.png",
      },
      {
        n: 42,
        nodeId: "297:80389",
        figmaName: "Flow 1 - 42",
        title: "Tracking · modal",
        note: "Tracking con sheet o código de entrega.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-1/flow-1-42.png",
      },
      {
        n: 43,
        nodeId: "297:80373",
        figmaName: "Flow 1 - 43",
        title: "Tracking · modal",
        note: "Tracking con sheet o código de entrega.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-1/flow-1-43.png",
      },
      {
        n: 44,
        nodeId: "295:75136",
        figmaName: "Flow 1 - 44",
        title: "Cover",
        note: "Portada o corte de diseño (slides 2.0) en el flujo de Figma.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-1/flow-1-44.png",
      },
      {
        n: 45,
        nodeId: "297:77577",
        figmaName: "Flow 1 - 45",
        title: "Pedido",
        note: "Pantalla de pedido / confirmación.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-1/flow-1-45.png",
      },
      {
        n: 46,
        nodeId: "297:77503",
        figmaName: "Flow 1 - 46",
        title: "Resumen de fees",
        note: "Resumen post-pedido con fees.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-1/flow-1-46.png",
      },
      {
        n: 47,
        nodeId: "297:78241",
        figmaName: "Flow 1 - 47",
        title: "Pedido",
        note: "Pantalla de pedido / confirmación.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-1/flow-1-47.png",
      },
    ],
  },
  {
    id: "flujo-2",
    figma: 2,
    label: "Flujo 2 · Turbo+Turbo",
    short: "Turbo+Turbo",
    description: "Figma 2nd review · Turbo + Turbo. Combinar ítems de dos bodegas de la misma cadena cuando una no cubre el stock.",
    screens: [
      {
        n: 1,
        nodeId: "259:77016",
        figmaName: "Flow 2 - 1",
        title: "Cover",
        note: "Portada o corte de diseño (slides 2.0) en el flujo de Figma.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-2/flow-2-01.png",
      },
      {
        n: 2,
        nodeId: "297:89513",
        figmaName: "Flow 2 - 2",
        title: "Cover",
        note: "Portada o corte de diseño (slides 2.0) en el flujo de Figma.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-2/flow-2-02.png",
      },
      {
        n: 3,
        nodeId: "297:84565",
        figmaName: "Flow 2 - 3",
        title: "Modal",
        note: "Modal o bottom sheet sobre la pantalla.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-2/flow-2-03.png",
      },
      {
        n: 4,
        nodeId: "297:84354",
        figmaName: "Flow 2 - 4",
        title: "all",
        note: "Pantalla del flujo en Figma.",
        width: 375,
        height: 1548,
        src: "./assets/group-order/flujo-2/flow-2-04.png",
      },
      {
        n: 5,
        nodeId: "297:84219",
        figmaName: "Flow 2 - 5",
        title: "Turbo · pasillos",
        note: "Navegación de pasillos Turbo.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-2/flow-2-05.png",
      },
      {
        n: 6,
        nodeId: "297:84137",
        figmaName: "Flow 2 - 6",
        title: "Turbo · pasillos",
        note: "Navegación de pasillos Turbo.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-2/flow-2-06.png",
      },
      {
        n: 7,
        nodeId: "297:83991",
        figmaName: "Flow 2 - 7",
        title: "Fichas de producto",
        note: "Varias fichas de producto en el canvas (no es un iPhone 375).",
        width: 664,
        height: 1164,
        src: "./assets/group-order/flujo-2/flow-2-07.png",
      },
      {
        n: 8,
        nodeId: "297:83779",
        figmaName: "Flow 2 - 8",
        title: "all",
        note: "Pantalla del flujo en Figma.",
        width: 375,
        height: 1548,
        src: "./assets/group-order/flujo-2/flow-2-08.png",
      },
      {
        n: 9,
        nodeId: "297:83604",
        figmaName: "Flow 2 - 9",
        title: "Turbo",
        note: "Home / mundos Turbo.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-2/flow-2-09.png",
      },
      {
        n: 10,
        nodeId: "297:83422",
        figmaName: "Flow 2 - 10",
        title: "Turbo · canasta",
        note: "Home Turbo con canasta.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-2/flow-2-10.png",
      },
      {
        n: 11,
        nodeId: "297:83241",
        figmaName: "Flow 2 - 11",
        title: "Turbo · canasta",
        note: "Home Turbo con canasta.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-2/flow-2-11.png",
      },
      {
        n: 12,
        nodeId: "297:83060",
        figmaName: "Flow 2 - 12",
        title: "Turbo · canasta",
        note: "Home Turbo con canasta.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-2/flow-2-12.png",
      },
      {
        n: 13,
        nodeId: "297:82878",
        figmaName: "Flow 2 - 13",
        title: "Turbo · canasta",
        note: "Home Turbo con canasta.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-2/flow-2-13.png",
      },
      {
        n: 14,
        nodeId: "297:82697",
        figmaName: "Flow 2 - 14",
        title: "Turbo · canasta",
        note: "Home Turbo con canasta.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-2/flow-2-14.png",
      },
      {
        n: 15,
        nodeId: "297:82521",
        figmaName: "Flow 2 - 15",
        title: "Turbo · canasta",
        note: "Home Turbo con canasta.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-2/flow-2-15.png",
      },
      {
        n: 16,
        nodeId: "259:77014",
        figmaName: "Flow 2 - 16",
        title: "Cover",
        note: "Portada o corte de diseño (slides 2.0) en el flujo de Figma.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-2/flow-2-16.png",
      },
      {
        n: 17,
        nodeId: "259:77075",
        figmaName: "Flow 2 - 17",
        title: "Canasta",
        note: "Canasta agrupada.",
        width: 375,
        height: 1524,
        src: "./assets/group-order/flujo-2/flow-2-17.png",
      },
      {
        n: 18,
        nodeId: "262:79332",
        figmaName: "Flow 2 - 18",
        title: "Canasta",
        note: "Canasta agrupada.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-2/flow-2-18.png",
      },
      {
        n: 19,
        nodeId: "262:79807",
        figmaName: "Flow 2 - 19",
        title: "Canasta",
        note: "Canasta agrupada.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-2/flow-2-19.png",
      },
      {
        n: 20,
        nodeId: "262:78841",
        figmaName: "Flow 2 - 20",
        title: "Canasta",
        note: "Canasta agrupada.",
        width: 375,
        height: 1524,
        src: "./assets/group-order/flujo-2/flow-2-20.png",
      },
      {
        n: 21,
        nodeId: "263:83130",
        figmaName: "Flow 2 - 21",
        title: "Cover",
        note: "Portada o corte de diseño (slides 2.0) en el flujo de Figma.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-2/flow-2-21.png",
      },
      {
        n: 22,
        nodeId: "297:89649",
        figmaName: "Flow 2 - 22",
        title: "Checkout",
        note: "Checkout (dirección / pago).",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-2/flow-2-22.png",
      },
      {
        n: 23,
        nodeId: "263:83279",
        figmaName: "Flow 2 - 23",
        title: "Checkout",
        note: "Checkout (dirección / pago).",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-2/flow-2-23.png",
      },
      {
        n: 24,
        nodeId: "263:84613",
        figmaName: "Flow 2 - 24",
        title: "Checkout · modal",
        note: "Checkout con modal.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-2/flow-2-24.png",
      },
      {
        n: 25,
        nodeId: "263:84018",
        figmaName: "Flow 2 - 25",
        title: "Cover",
        note: "Portada o corte de diseño (slides 2.0) en el flujo de Figma.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-2/flow-2-25.png",
      },
      {
        n: 26,
        nodeId: "272:59663",
        figmaName: "Flow 2 - 26",
        title: "Checkout",
        note: "Checkout unificado.",
        width: 375,
        height: 1581,
        src: "./assets/group-order/flujo-2/flow-2-26.png",
      },
      {
        n: 27,
        nodeId: "298:89901",
        figmaName: "Flow 2 - 27",
        title: "Checkout",
        note: "Checkout unificado.",
        width: 375,
        height: 1677,
        src: "./assets/group-order/flujo-2/flow-2-27.png",
      },
      {
        n: 28,
        nodeId: "299:90326",
        figmaName: "Flow 2 - 28",
        title: "Cover",
        note: "Portada o corte de diseño (slides 2.0) en el flujo de Figma.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-2/flow-2-28.png",
      },
      {
        n: 29,
        nodeId: "299:90348",
        figmaName: "Flow 2 - 29",
        title: "Resumen de fees",
        note: "Resumen post-pedido con fees.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-2/flow-2-29.png",
      },
      {
        n: 30,
        nodeId: "299:90332",
        figmaName: "Flow 2 - 30",
        title: "Cover",
        note: "Portada o corte de diseño (slides 2.0) en el flujo de Figma.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-2/flow-2-30.png",
      },
      {
        n: 31,
        nodeId: "300:90667",
        figmaName: "Flow 2 - 31",
        title: "Pedido creado",
        note: "Confirmación de la orden padre.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-2/flow-2-31.png",
      },
      {
        n: 32,
        nodeId: "299:90338",
        figmaName: "Flow 2 - 32",
        title: "Cover",
        note: "Portada o corte de diseño (slides 2.0) en el flujo de Figma.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-2/flow-2-32.png",
      },
      {
        n: 33,
        nodeId: "300:90767",
        figmaName: "Flow 2 - 33",
        title: "Tracking",
        note: "Order tracking / detalle de sub-orden.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-2/flow-2-33.png",
      },
      {
        n: 34,
        nodeId: "300:91778",
        figmaName: "Flow 2 - 34",
        title: "Tracking · tooltip",
        note: "Detalle de tracking con tooltip.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-2/flow-2-34.png",
      },
      {
        n: 35,
        nodeId: "300:91945",
        figmaName: "Flow 2 - 35",
        title: "Tracking · mapa",
        note: "Order tracking con mapa de una sub-orden.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-2/flow-2-35.png",
      },
    ],
  },
  {
    id: "flujo-3",
    figma: 3,
    label: "Flujo 3 · Turbo Search+Retailers",
    short: "Search+Retail",
    description: "Figma 2nd review · Turbo (Search) + Retailers. Búsqueda con ETA por producto y canasta multi-tienda.",
    screens: [
      {
        n: 1,
        nodeId: "348:96050",
        figmaName: "Flow 3 - 1",
        title: "Cover",
        note: "Portada o corte de diseño (slides 2.0) en el flujo de Figma.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-3/flow-3-01.png",
      },
      {
        n: 2,
        nodeId: "327:103471",
        figmaName: "Flow 3 - 2",
        title: "Cover",
        note: "Portada o corte de diseño (slides 2.0) en el flujo de Figma.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-3/flow-3-02.png",
      },
      {
        n: 3,
        nodeId: "322:85341",
        figmaName: "Flow 3 - 3",
        title: "Búsqueda",
        note: "Resultados de búsqueda multi-tienda con ETA por producto.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-3/flow-3-03.png",
      },
      {
        n: 4,
        nodeId: "319:83081",
        figmaName: "Flow 3 - 4",
        title: "Búsqueda · canasta",
        note: "Resultados de búsqueda multi-tienda con canasta visible.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-3/flow-3-04.png",
      },
      {
        n: 5,
        nodeId: "322:85722",
        figmaName: "Flow 3 - 5",
        title: "Búsqueda · canasta",
        note: "Resultados de búsqueda multi-tienda con canasta visible.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-3/flow-3-05.png",
      },
      {
        n: 6,
        nodeId: "322:86750",
        figmaName: "Flow 3 - 6",
        title: "Búsqueda · canasta",
        note: "Resultados de búsqueda multi-tienda con canasta visible.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-3/flow-3-06.png",
      },
      {
        n: 7,
        nodeId: "322:87117",
        figmaName: "Flow 3 - 7",
        title: "Búsqueda · canasta",
        note: "Resultados de búsqueda multi-tienda con canasta visible.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-3/flow-3-07.png",
      },
      {
        n: 8,
        nodeId: "319:82431",
        figmaName: "Flow 3 - 8",
        title: "Canasta",
        note: "Canasta agrupada.",
        width: 375,
        height: 2128,
        src: "./assets/group-order/flujo-3/flow-3-08.png",
      },
      {
        n: 9,
        nodeId: "324:90717",
        figmaName: "Flow 3 - 9",
        title: "Canasta",
        note: "Canasta agrupada.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-3/flow-3-09.png",
      },
      {
        n: 10,
        nodeId: "324:91471",
        figmaName: "Flow 3 - 10",
        title: "Canasta",
        note: "Canasta agrupada.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-3/flow-3-10.png",
      },
      {
        n: 11,
        nodeId: "324:92424",
        figmaName: "Flow 3 - 11",
        title: "Canasta",
        note: "Canasta agrupada.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-3/flow-3-11.png",
      },
      {
        n: 12,
        nodeId: "327:102600",
        figmaName: "Flow 3 - 12",
        title: "all",
        note: "Pantalla del flujo en Figma.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-3/flow-3-12.png",
      },
      {
        n: 13,
        nodeId: "327:103487",
        figmaName: "Flow 3 - 13",
        title: "Cover",
        note: "Portada o corte de diseño (slides 2.0) en el flujo de Figma.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-3/flow-3-13.png",
      },
      {
        n: 14,
        nodeId: "344:88921",
        figmaName: "Flow 3 - 14",
        title: "Canasta",
        note: "Canasta agrupada.",
        width: 375,
        height: 1852,
        src: "./assets/group-order/flujo-3/flow-3-14.png",
      },
      {
        n: 15,
        nodeId: "324:93237",
        figmaName: "Flow 3 - 15",
        title: "Canasta",
        note: "Canasta agrupada.",
        width: 375,
        height: 1852,
        src: "./assets/group-order/flujo-3/flow-3-15.png",
      },
      {
        n: 16,
        nodeId: "326:94528",
        figmaName: "Flow 3 - 16",
        title: "Canasta",
        note: "Canasta agrupada.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-3/flow-3-16.png",
      },
      {
        n: 17,
        nodeId: "327:103942",
        figmaName: "Flow 3 - 17",
        title: "Checkout · modal",
        note: "Checkout con modal.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-3/flow-3-17.png",
      },
      {
        n: 18,
        nodeId: "326:95653",
        figmaName: "Flow 3 - 18",
        title: "Checkout · modal",
        note: "Checkout con modal.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-3/flow-3-18.png",
      },
      {
        n: 19,
        nodeId: "348:95736",
        figmaName: "Flow 3 - 19",
        title: "Tienda · canasta",
        note: "Storefront con el botón de canasta.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-3/flow-3-19.png",
      },
      {
        n: 20,
        nodeId: "336:108929",
        figmaName: "Flow 3 - 20",
        title: "Cover",
        note: "Portada o corte de diseño (slides 2.0) en el flujo de Figma.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-3/flow-3-20.png",
      },
      {
        n: 21,
        nodeId: "344:84232",
        figmaName: "Flow 3 - 21",
        title: "Checkout",
        note: "Checkout (dirección / pago).",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-3/flow-3-21.png",
      },
      {
        n: 22,
        nodeId: "344:85644",
        figmaName: "Flow 3 - 22",
        title: "Checkout",
        note: "Checkout (dirección / pago).",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-3/flow-3-22.png",
      },
      {
        n: 23,
        nodeId: "344:88256",
        figmaName: "Flow 3 - 23",
        title: "Checkout",
        note: "Checkout (dirección / pago).",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-3/flow-3-23.png",
      },
      {
        n: 24,
        nodeId: "336:108927",
        figmaName: "Flow 3 - 24",
        title: "Cover",
        note: "Portada o corte de diseño (slides 2.0) en el flujo de Figma.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-3/flow-3-24.png",
      },
      {
        n: 25,
        nodeId: "344:87499",
        figmaName: "Flow 3 - 25",
        title: "Checkout",
        note: "Checkout unificado.",
        width: 375,
        height: 1785,
        src: "./assets/group-order/flujo-3/flow-3-25.png",
      },
      {
        n: 26,
        nodeId: "344:88484",
        figmaName: "Flow 3 - 26",
        title: "Checkout",
        note: "Checkout unificado.",
        width: 375,
        height: 1581,
        src: "./assets/group-order/flujo-3/flow-3-26.png",
      },
      {
        n: 27,
        nodeId: "336:108925",
        figmaName: "Flow 3 - 27",
        title: "Cover",
        note: "Portada o corte de diseño (slides 2.0) en el flujo de Figma.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-3/flow-3-27.png",
      },
      {
        n: 28,
        nodeId: "344:90230",
        figmaName: "Flow 3 - 28",
        title: "Pedido",
        note: "Pantalla de pedido / confirmación.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-3/flow-3-28.png",
      },
      {
        n: 29,
        nodeId: "347:90551",
        figmaName: "Flow 3 - 29",
        title: "Resumen de fees",
        note: "Resumen post-pedido con fees.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-3/flow-3-29.png",
      },
      {
        n: 30,
        nodeId: "336:108923",
        figmaName: "Flow 3 - 30",
        title: "Cover",
        note: "Portada o corte de diseño (slides 2.0) en el flujo de Figma.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-3/flow-3-30.png",
      },
      {
        n: 31,
        nodeId: "347:90731",
        figmaName: "Flow 3 - 31",
        title: "Pedido creado",
        note: "Confirmación de la orden padre.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-3/flow-3-31.png",
      },
      {
        n: 32,
        nodeId: "336:108921",
        figmaName: "Flow 3 - 32",
        title: "Cover",
        note: "Portada o corte de diseño (slides 2.0) en el flujo de Figma.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-3/flow-3-32.png",
      },
      {
        n: 33,
        nodeId: "347:91133",
        figmaName: "Flow 3 - 33",
        title: "Tracking",
        note: "Order tracking / detalle de sub-orden.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-3/flow-3-33.png",
      },
      {
        n: 34,
        nodeId: "347:91103",
        figmaName: "Flow 3 - 34",
        title: "Tracking · tooltip",
        note: "Detalle de tracking con tooltip.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-3/flow-3-34.png",
      },
      {
        n: 35,
        nodeId: "347:91081",
        figmaName: "Flow 3 - 35",
        title: "Tracking · mapa",
        note: "Order tracking con mapa de una sub-orden.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-3/flow-3-35.png",
      },
    ],
  },
  {
    id: "flujo-4",
    figma: 4,
    label: "Flujo 4 · Retail+Retail",
    short: "Retail+Retail",
    description: "Figma 2nd review · Retail + Retail. Decathlon + Pull & Bear + Mango: varias entregas, un total.",
    screens: [
      {
        n: 1,
        nodeId: "258:76817",
        figmaName: "Flow 4 - 1",
        title: "Cover",
        note: "Portada o corte de diseño (slides 2.0) en el flujo de Figma.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-4/flow-4-01.png",
      },
      {
        n: 2,
        nodeId: "290:63994",
        figmaName: "Flow 4 - 2",
        title: "Cover",
        note: "Portada o corte de diseño (slides 2.0) en el flujo de Figma.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-4/flow-4-02.png",
      },
      {
        n: 3,
        nodeId: "289:61601",
        figmaName: "Flow 4 - 3",
        title: "Retail",
        note: "Browse de retail.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-4/flow-4-03.png",
      },
      {
        n: 4,
        nodeId: "289:61585",
        figmaName: "Flow 4 - 4",
        title: "Canasta",
        note: "Canasta agrupada.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-4/flow-4-04.png",
      },
      {
        n: 5,
        nodeId: "289:61570",
        figmaName: "Flow 4 - 5",
        title: "Canasta",
        note: "Canasta agrupada.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-4/flow-4-05.png",
      },
      {
        n: 6,
        nodeId: "289:61554",
        figmaName: "Flow 4 - 6",
        title: "Canasta",
        note: "Canasta agrupada.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-4/flow-4-06.png",
      },
      {
        n: 7,
        nodeId: "289:61539",
        figmaName: "Flow 4 - 7",
        title: "Canasta",
        note: "Canasta agrupada.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-4/flow-4-07.png",
      },
      {
        n: 8,
        nodeId: "289:61524",
        figmaName: "Flow 4 - 8",
        title: "Canasta",
        note: "Canasta agrupada.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-4/flow-4-08.png",
      },
      {
        n: 9,
        nodeId: "319:80859",
        figmaName: "Flow 4 - 9",
        title: "Cover",
        note: "Portada o corte de diseño (slides 2.0) en el flujo de Figma.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-4/flow-4-09.png",
      },
      {
        n: 10,
        nodeId: "336:108460",
        figmaName: "Flow 4 - 10",
        title: "body",
        note: "Pantalla del flujo en Figma.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-4/flow-4-10.png",
      },
      {
        n: 11,
        nodeId: "307:77889",
        figmaName: "Flow 4 - 11",
        title: "Tus canastas",
        note: "Home de canastas agrupadas.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-4/flow-4-11.png",
      },
      {
        n: 12,
        nodeId: "258:76807",
        figmaName: "Flow 4 - 12",
        title: "Cover",
        note: "Portada o corte de diseño (slides 2.0) en el flujo de Figma.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-4/flow-4-12.png",
      },
      {
        n: 13,
        nodeId: "255:68301",
        figmaName: "Flow 4 - 13",
        title: "Canasta",
        note: "Canasta agrupada.",
        width: 375,
        height: 1898,
        src: "./assets/group-order/flujo-4/flow-4-13.png",
      },
      {
        n: 14,
        nodeId: "255:71590",
        figmaName: "Flow 4 - 14",
        title: "Canasta",
        note: "Canasta agrupada.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-4/flow-4-14.png",
      },
      {
        n: 15,
        nodeId: "255:71042",
        figmaName: "Flow 4 - 15",
        title: "Canasta",
        note: "Canasta agrupada.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-4/flow-4-15.png",
      },
      {
        n: 16,
        nodeId: "258:72330",
        figmaName: "Flow 4 - 16",
        title: "Canasta",
        note: "Canasta agrupada.",
        width: 375,
        height: 1302,
        src: "./assets/group-order/flujo-4/flow-4-16.png",
      },
      {
        n: 17,
        nodeId: "259:76922",
        figmaName: "Flow 4 - 17",
        title: "Cover",
        note: "Portada o corte de diseño (slides 2.0) en el flujo de Figma.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-4/flow-4-17.png",
      },
      {
        n: 18,
        nodeId: "263:81858",
        figmaName: "Flow 4 - 18",
        title: "Checkout",
        note: "Checkout (dirección / pago).",
        width: 375,
        height: 860,
        src: "./assets/group-order/flujo-4/flow-4-18.png",
      },
      {
        n: 19,
        nodeId: "263:84178",
        figmaName: "Flow 4 - 19",
        title: "Checkout",
        note: "Checkout (dirección / pago).",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-4/flow-4-19.png",
      },
      {
        n: 20,
        nodeId: "290:64000",
        figmaName: "Flow 4 - 20",
        title: "Checkout · modal",
        note: "Checkout con modal.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-4/flow-4-20.png",
      },
      {
        n: 21,
        nodeId: "290:64418",
        figmaName: "Flow 4 - 21",
        title: "Checkout",
        note: "Checkout (dirección / pago).",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-4/flow-4-21.png",
      },
      {
        n: 22,
        nodeId: "291:68758",
        figmaName: "Flow 4 - 22",
        title: "Sheet",
        note: "Bottom sheet o selector a pantalla completa.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-4/flow-4-22.png",
      },
      {
        n: 23,
        nodeId: "259:77002",
        figmaName: "Flow 4 - 23",
        title: "Cover",
        note: "Portada o corte de diseño (slides 2.0) en el flujo de Figma.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-4/flow-4-23.png",
      },
      {
        n: 24,
        nodeId: "264:85746",
        figmaName: "Flow 4 - 24",
        title: "Checkout",
        note: "Checkout unificado.",
        width: 375,
        height: 1785,
        src: "./assets/group-order/flujo-4/flow-4-24.png",
      },
      {
        n: 25,
        nodeId: "264:89252",
        figmaName: "Flow 4 - 25",
        title: "Checkout",
        note: "Checkout unificado.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-4/flow-4-25.png",
      },
      {
        n: 26,
        nodeId: "264:88505",
        figmaName: "Flow 4 - 26",
        title: "Checkout",
        note: "Checkout unificado.",
        width: 375,
        height: 1881,
        src: "./assets/group-order/flujo-4/flow-4-26.png",
      },
      {
        n: 27,
        nodeId: "293:69941",
        figmaName: "Flow 4 - 27",
        title: "Checkout",
        note: "Checkout unificado.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-4/flow-4-27.png",
      },
      {
        n: 28,
        nodeId: "293:70383",
        figmaName: "Flow 4 - 28",
        title: "Checkout",
        note: "Checkout unificado.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-4/flow-4-28.png",
      },
      {
        n: 29,
        nodeId: "293:69153",
        figmaName: "Flow 4 - 29",
        title: "Cover",
        note: "Portada o corte de diseño (slides 2.0) en el flujo de Figma.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-4/flow-4-29.png",
      },
      {
        n: 30,
        nodeId: "293:71940",
        figmaName: "Flow 4 - 30",
        title: "Pedido",
        note: "Pantalla de pedido / confirmación.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-4/flow-4-30.png",
      },
      {
        n: 31,
        nodeId: "293:71867",
        figmaName: "Flow 4 - 31",
        title: "Resumen de fees",
        note: "Resumen post-pedido con fees.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-4/flow-4-31.png",
      },
      {
        n: 32,
        nodeId: "293:72180",
        figmaName: "Flow 4 - 32",
        title: "Cover",
        note: "Portada o corte de diseño (slides 2.0) en el flujo de Figma.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-4/flow-4-32.png",
      },
      {
        n: 33,
        nodeId: "293:71007",
        figmaName: "Flow 4 - 33",
        title: "Pedido creado",
        note: "Confirmación de la orden padre.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-4/flow-4-33.png",
      },
      {
        n: 34,
        nodeId: "293:72186",
        figmaName: "Flow 4 - 34",
        title: "Cover",
        note: "Portada o corte de diseño (slides 2.0) en el flujo de Figma.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-4/flow-4-34.png",
      },
      {
        n: 35,
        nodeId: "293:72269",
        figmaName: "Flow 4 - 35",
        title: "Tracking",
        note: "Order tracking / detalle de sub-orden.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-4/flow-4-35.png",
      },
      {
        n: 36,
        nodeId: "295:74194",
        figmaName: "Flow 4 - 36",
        title: "Tracking · tooltip",
        note: "Detalle de tracking con tooltip.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-4/flow-4-36.png",
      },
      {
        n: 37,
        nodeId: "295:74377",
        figmaName: "Flow 4 - 37",
        title: "Tracking · mapa",
        note: "Order tracking con mapa de una sub-orden.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-4/flow-4-37.png",
      },
      {
        n: 38,
        nodeId: "780:39352",
        figmaName: "Flow 4 - 38",
        title: "Tus canastas",
        note: "Home de canastas agrupadas.",
        width: 375,
        height: 812,
        src: "./assets/group-order/flujo-4/flow-4-38.png",
      },
    ],
  },
];
